const DATABASE_NAME = '@gameplay';
const COLLECTION_USERS = `${DATABASE_NAME}:users`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export {
    DATABASE_NAME,
    COLLECTION_USERS,
    COLLECTION_APPOINTMENTS,
};
